name: Othello C++/Makefile Build 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-boost
      run: sudo apt-get install libboost-all-dev
    - name: install-valgrind
      run: sudo apt-get install valgrind
    - name: make
      run: make
    - name: unit-testing
      run: make check
    - name: memory-leak-testing
      run: make check-for-leaks